import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const latestPost = api.post.getLatest.useQuery();
  const createPostMutation = api.post.create.useMutation({
    onSuccess: () => {
      latestPost.refetch();
    },
  });
  const createPost = () => {
    createPostMutation.mutate({
      name: `New Post!`,
    });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <button
            type="button"
            className="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
            onClick={createPost}
          >
            Create Post
          </button>
          <p className="">
            Latest Post:
            {latestPost.data && (
              <span>
                {`${latestPost.data.name}, Created: ${latestPost.data.createdAt.toString()}`}
              </span>
            )}
          </p>
        </div>
      </main>
    </>
  );
}
